name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: '镜像版本'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dockerfile: [
          { path: './server/core-service/Dockerfile', name: 'timebox-core-service', context: './server/core-service' },
          { path: './server/ocr-service/Dockerfile', name: 'timebox-ocr-service', context: './server/ocr-service' },
          { path: './server/ocr-service/Dockerfile.cuda', name: 'timebox-ocr-service-cuda', context: './server/ocr-service' }
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 添加 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 构建前端项目
      - name: Build Frontend
        run: |
          cd client
          yarn
          yarn build
          
      # 复制构建文件到 core-service
      - name: Copy Frontend Build
        run: |
          mkdir -p server/core-service/static
          cp -r client/dist/* server/core-service/static/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Context directory contents:"
          ls -la ${{ matrix.dockerfile.context }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.dockerfile.context }}
          file: ${{ matrix.dockerfile.path }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dockerfile.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dockerfile.name }}:${{ github.event.inputs.version || 'latest' }} 