name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: '镜像版本'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dockerfile: [
          { path: './server/core-service/Dockerfile', name: 'core-service', context: './server/core-service' },
          { path: './server/ocr-service/Dockerfile', name: 'ocr-service', context: './server/ocr-service' },
          { path: './server/ocr-service/Dockerfile.cuda', name: 'ocr-service-cuda', context: './server/ocr-service' }
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.dockerfile.context }}
          file: ${{ matrix.dockerfile.path }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dockerfile.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dockerfile.name }}:${{ github.event.inputs.version || 'latest' }} 